[project]
name = "jsondumps_workspace"
version = "0.1.0"
description = "Workspace for jsondumps"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["core"]

[tool.uv.sources]
core = { workspace = true }
api = { workspace = true }

[tool.uv.workspace]
members = ["packages/*"]

[tool.ruff.lint]
select = ["T100"]
